import React from 'react'
import { useIpynbNotebookParagraphs } from '../hooks/ipynb'
import ArticleCell from '../components/Article/ArticleCell'

// Stories for hoks and methds, following Josh Farrant https://farrant.me/posts/documenting-react-hooks-with-storybook
// accessed 04 01 2023
export default {
  title: 'tests/Notebook with figures',
  component: ArticleCell,
  argTypes: {
    metadata: { control: { type: 'object' }, defaultValue: {} },
  },
}

const Template = ({ cells, metadata }) => {
  const articleTree = useIpynbNotebookParagraphs({
    id: 'memoid',
    cells,
    metadata,
  })

  console.debug('[Article] loading articleTree paragraphs:', articleTree.paragraphs.length)

  return [articleTree.paragraphs.map((p) => <ArticleCell key={p.id} {...p} />)]
}
export const Default = Template.bind({})

Default.args = {
  metadata: {},
  cells: [
    {
      cell_type: 'code',
      execution_count: 103,
      metadata: {
        jdh: {
          module: 'object',
          object: {
            source: ['figure 1: Distribution of the lexemes in Tacitus'],
            type: 'image',
          },
        },
        tags: ['narrative', 'hermeneutics', 'figure-1', 'h-362px', 'w-354px'],
      },
      outputs: [
        {
          data: {
            'text/markdown': [
              'There are __186 occurrences__ of the three main lexemes of the crowd in Tacitus: __123 occurrences__ of _vulgus_ (66.13%), __45 occurrences__ of _multitudo_ (24.19%) and __18 occurrences__ of _turba_ (9.68%).',
            ],
            'text/plain': ['<IPython.core.display.Markdown object>'],
          },
          metadata: {},
          output_type: 'display_data',
        },
        {
          data: {
            'text/plain': ["Text(0.5,1,'figure 1: Distribution of the lexemes in Tacitus')"],
          },
          execution_count: 103,
          metadata: {},
          output_type: 'execute_result',
        },
        {
          data: {
            'image/png':
              'iVBORw0KGgoAAAANSUhEUgAABLIAAAKkCAIAAACbIYESAAAKrmlDQ1BJQ0MgUHJvZmlsZQAASImVlwdUU9kWhs+96SGhJSCd0Jv0FkBKCC2A9C4qIQkklBgDoYkNGRyBsaAigmVER0UUHAsgY0Es2AbFAqjogAwCyjixYEPlXWARZuat9956+66zzpf/7rP3Pneds9YOAGQqWyTKgBUByBRmiyP8vWlx8Qk03DCAABl5nIErm5MlYoSFBQPEZue/2/tuxBuxe5ZTsf79/X81JS4viwMAFIZwMjeLk4nwKWRIOSJxNgCoA4hukJstmuJrCFPFSIEI901x6gxLpzh5mtHoaZ+oCCbCagDgSWy2OBUAkiGi03I4qUgckg/CNkKuQIgw8ht4ZGYu4yKM5AWmiI8I4an49OS/xEn9W8xkWUw2O1XGM3uZNryPIEuUwc7/Pz/H/7bMDMlsDmNkkPjigAhkRuqCetOXBclYmBwSOssC7rT/NPMlAdGzzMliJswyl+0TJFubERI8yykCP5YsTjYrapZ5Wb6RsyxeFiHLlSJmMmaZLZ7LK0mPlul8HksWv4AfFTvLOYKYkFnOSo8MmvNhynSxJEJWP0/o7z2X10+298ysv+xXwJKtzeZHBcj2zp6rnydkzMXMipPVxuX5+M75RMv8RdneslyijDCZPy/DX6Zn5UTK1mYjB3JubZjsG6axA8NmGfgAXxCMPDQQDeyBHfLYg3Dgm83LmzqjgLlMlC8WpPKzaQzklvFoLCHHaj7NzsbOHoCpOztzJN72Tt9FSBU/pxVdBGDBegSkc1rIcwBOnkOOD29OM7IGQAHRrvRwJOKcGW3qOgEMIAIFQAXqQAcYAFNgidTmBNyAF1JxIAgFUSAeLAEcwAeZQAxyQSFYC0pAGdgMtoNqsBfsB4fBMXACNIOz4CK4Cm6CO+ABeAz6wRB4CaTgPZiAIAgHkSEKpA7pQkaQBWQH0SEPyBcKhiKgeCgJSoWEkAQqhNZBZVAFVA3tg+qgn6Ez0EXoOtQFPYQGoFHoDfQZRsEkmAprw8awNUyHGXAQHAUvhlPh5XABXAxvhKvgWvgo3ARfhG/CD+B++CU8jgIoOZQqSg9liaKjmKhQVAIqBSVGrUKVoipRtagGVCuqA3UP1Y8aQ31CY9EUNA1tiXZDB6Cj0Rz0cvQqdDm6Gn0Y3YS+jL6HHkBL0d8wZIwWxgLjimFh4jCpmFxMCaYScxBzGnMF8wAzhHmPxWJVsSZYZ2wANh6bhl2BLcfuxjZi27Bd2EHsOA6HU8dZ4NxxoTg2LhtXgtuJO4q7gLuLG8J9xMvhdfF2eD98Al6IL8JX4o/gz+Pv4ofxEwRFghHBlRBK4BLyCZsIBwithNuEIcIEUYloQnQnRhHTiGuJVcQG4hViH/GtnJycvpyLXLicQG6NXJXccblrcgNyn0jKJHMSk5RIkpA2kg6R2kgPSW/JZLIx2YucQM4mbyTXkS+Rn5I/ylPkreRZ8lz51fI18k3yd+VfKRAUjBQYCksUChQqFU4q3FYYUyQoGisyFdmKqxRrFM8o9iiOK1GUbJVClTKVypWOKF1XGlHGKRsr+ypzlYuV9ytfUh6koCgGFCaFQ1lHOUC5QhmiYqkmVBY1jVpGPUbtpEpVlFUcVGJU8lRqVM6p9KuiVI1VWaoZqptUT6h2q36epz2PMY83b8O8hnl3531Q01TzUuOplao1qj1Q+6xOU/dVT1ffot6s/kQDrWGuEa6Rq7FH44rGmCZV002To1mqeULzkRasZa4VobVCa7/WLa1xbR1tf22R9k7tS9pjOqo6XjppOtt0zuuM6lJ0PXQFutt0L+i+oKnQGLQMWhXtMk2qp6UXoCfR26fXqTehb6IfrV+k36j/xIBoQDdIMdhm0G4gNdQ1XGhYaFhv+MiIYEQ34hvtMOow+mBsYhxrvN642XjERM2EZVJgUm/SZ0o29TRdblpret8Ma0Y3SzfbbXbHHDZ3NOeb15jftoAtnCwEFrstuuZj5rvMF86vnd9jSbJkWOZY1lsOWKlaBVsVWTVbvbI2tE6w3mLdYf3NxtEmw+aAzWNbZdtA2yLbVts3duZ2HLsau/v2ZHs/+9X2LfavHSwceA57HHodKY4LHdc7tjt+dXJ2Ejs1OI06GzonOe9y7qFT6WH0cvo1F4yLt8tql7Mun1ydXLNdT7j+6Wbplu52xG1kgckC3oIDCwbd9d3Z7vvc+z1oHkkeP3r0e+p5sj1rPZ95GXhxvQ56DTPMGGmMo4xX3jbeYu/T3h+YrsyVzDYflI+/T6lPp6+yb7Rvte9TP32/VL96P6m/o/8K/7YATEBQwJaAHpY2i8OqY0kDnQNXBl4OIgVFBlUHPQs2DxYHty6EFwYu3LqwL8QoRBjSHApCWaFbQ5+EmYQtD/slHBseFl4T/jzCNqIwoiOSErk08kjk+yjvqE1Rj6NNoyXR7TEKMYkxdTEfYn1iK2L746zjVsbdjNeIF8S3JOASYhIOJowv8l20fdFQomNiSWL3YpPFeYuvL9FYkrHk3FKFpeylJ5MwSbFJR5K+sEPZtezxZFbyrmQph8nZwXnJ9eJu447y3HkVvOEU95SKlJFU99StqaN8T34lf0zAFFQLXqcFpO1N+5Aemn4ofTIjNqMxE5+ZlHlGqCxMF15eprMsb1mXyEJUIupf7rp8+3KpOEh8MAvKWpzVkk1FmqNbElPJd5KBHI+cmpyPuTG5J/OU8oR5t/LN8zfkDxf4Ffy0Ar2Cs6K9UK9wbeHASsbKfaugVcmr2lcbrC5ePbTGf83htcS16Wt/LbIpqih6ty52XWuxdvGa4sHv/L+rL5EvEZf0rHdbv/d79PeC7zs32G/YueFbKbf0RplNWWXZl3JO+Y0fbH+o+mFyY8rGzk1Om/Zsxm4Wbu7e4rnlcIVSRUHF4NaFW5u20baVbnu3fen265UOlXt3EHdIdvRXBVe17DTcuXnnl2p+9YMa75rGXVq7Nuz6sJu7++4erz0Ne7X3lu39/KPgx959/vuaao1rK/dj9+fsf34g5kDHT/Sf6g5qHCw7+PWQ8FD/4YjDl+uc6+qOaB3ZVA/XS+pHjyYevXPM51hLg2XDvkbVxrLj4Ljk+Iufk37uPhF0ov0k/WTDKaNTu05TTpc2QU35TdJmfnN/S3xL15nAM+2tbq2nf7H65dBZvbM151TObTpPPF98fvJCwYXxNlHb2MXUi4PtS9sfX4q7dP9y+OXOK0FXrl31u3qpg9Fx4Zr7tbPXXa+fuUG/0XzT6WbTLcdbp391/PV0p1Nn023n2y13XO60di3oOn/X8+7Fez73rt5n3b/5IORBV3d0d29PYk9/L7d35GHGw9ePch5NPF7Th+krfaL4pPKp1tPa38x+a+x36j834DNw61nks8eDnMGXv2f9/mWo+Dn5eeWw7nDdiN3I2VG/0TsvFr0Yeil6OTFW8ofSH7temb469afXn7ekcdKh1+LXk2/K36q/PfTO4V37eNj40/eZ7yc+lH5U/3j4E/1Tx+fYz8MTuV9wX6q+mn1t/Rb0rW8yc3JSxBazp1sBFDLglBQA3hwCgBwPAOUOAMRFMz31tEEz/wOmCfwnnum7p80JgGNeAIStAcC3DeGpHgQZ8giHIXqUF4Dt7WVjtv+d7tWnTPEoAN6FDMeQ4N9Anwj8w2b6+L/U/c8ZTEV1AP+c/wWobAfs2g1wMAAAAIplWElmTU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAACQAAAAAQAAAJAAAAABAAOShgAHAAAAEgAAAHigAgAEAAAAAQAABLKgAwAEAAAAAQAAAqQAAAAAQVNDSUkAAABTY3JlZW5zaG90syoe1gAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAAddpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+Njc2PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjEyMDI8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpVc2VyQ29tbWVudD5TY3JlZW5zaG90PC9leGlmOlVzZXJDb21tZW50PgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KhjzCPAAAABxpRE9UAAAAAgAAAAAAAAFSAAAAKAAAAVIAAAFSAAApkMTULNUAABP9SURBVHja7d3BzS7FEUDRqmFScBpOwzGThtNwCmaKDXoyYv8sdM/ZfSA2I/7FVVV3790NAAAAVe9//vVvXwEAAKDmH7/+848snFmfAwAAIOu9sUQKAAAQzsI1LQQAAChnoSoEAABIZ+HnJlIAAIByFs4aFwIAAJSz0BYpAABAOgtVIQAAQNjjEwAAAMhCAAAAot5xEykAAEA5C89NpAAAAOks9A0AAADCnC0EAABIe9e4EAAAoJyFn28AAABQzsJz4wwAAEA5Cy2RAgAApLPQtBAAACCdhTPGhQAAAOksNC4EAAAIZ+GqQgAAgHIWmhYCAACks9CVMwAAAO0s/DxoDwAAUM5ChwsBAADCHp8AAACg7F1XzgAAAISZFgIAAKS95xsAAACUs3BHGAIAAISz8JwtBAAASGehKgQAAAhz5QwAAECaK2cAAADSTAsBAADSTAsBAADiWagLAQAAylnofQoAAIB0FhoWAgAAxLNQGAIAAISzcG2RAgAAlLNwVhYCAACEs/DWEikAAEA4C/dMCwEAAMJZ6GghAABAOgutkAIAAKSz0LAQAAAgnYWmhQAAAOksNC0EAABIZ+HnGwAAAJSz0BIpAABAOgu9Zg8AAJDOQq/ZAwAAyEIAAACqWWiJFAAAIJ2F3+hCAACAcBbe2iIFAAAIZ+GcaSEAAEDX4xMAAACUvWuJFAAAoJyFVkgBAADKLJECAACkWSIFAABoZ6GbSAEAANJZ6N1CAACAdhb6BgAAAOUsNCsEAABIZ+HN3MyPOPwxPFw//54/f/wTP/92P/0/7O/OT3+Gfvoz9NP/0v4M/fxpf2j/uzf6fvunfz1/+Q/89NPPn/PTF/DTT3+Gfvrppy/gp5//lz+0140zAAAAZe95oAIAAKCchZ6zBwAASGehaSEAAEA6C3/7ZCEAAEA4Cy2RAgAApLNwZCEAAEA7C30EAACAcBZaIgUAAEhn4RgXAgAAlLPwvs9XAAAA6GahK2cAAABkIQAAANUs/M5z9gAAALIQAACAZhZ6oAIAAKCdhb4BAABAOQvPtBAAAKCchaoQAAAgnYXzuXIGAAAgnIWWSAEAANJZuIaFAAAA5Sw8w0IAAABZCAAAQDQLLZECAACks/DzDQAAAMIenwAAAKDsnbFFCgAAkM5Cd84AAACEs3AfWQgAABDOwrNECgAAkM5Cw0IAAIByFq4uBAAAKGfhec8eAACgnIW/nSwEAAAIZ6EVUgAAgHQWercQAACgnYUrCwEAAMpZ6GwhAABAOQvPtBAAAKCchd6nAAAASGfhZ1gIAABQzkIXkQIAALSz0BIpAABAOgtNCwEAAMIenwAAAKDs/WyRAgAAlLPw8W4hAABAOQu/My0EAAAIZ6EdUgAAgHQWriVSAACAMDeRAgAApL1jWggAAFDOQg9UAAAApLPw3EQKAABQzsJ5LJECAACEs9BNpAAAALIQAACAahY6WwgAACALAQAAqGbhjiVSAACAcBZ6txAAACCdhefKGQAAgHIWjrOFAAAA5Sz8ZCEAAEA5C71bCAAAkM7CkYUAAADlLNxHFgIAAISz8DxQAQAAUM5CV84AAACks9DZQgAAgHQWikIAAIB2FpoWAgAAlLPQ0UIAAIB4FupCAACAchZaIgUAAGhnoY8AAAAQzsK1QwoAABD2+AQAAABllkgBAADSTAsBAADSTAsBAADaWejKGQAAgHQWmhYCAAC0s9A3AAAAKGfhjDAEAABIZ6EtUgAAgHAW7spCAACAcBbeWSIFAACQhQAAADSz0A4pAABAOgtHFwIAAJSz8GQhAABAOQvX2UIAAIByFpoWAgAAtLPQNwAAAEhnoWEhAABAOQvXuBAAAKCchaaFAAAA7Sz0DQAAAMIenwAAAKDM2UIAAIB2Fn7OFgIAAJSz0LAQAACgzNlCAAAAWQgAAEDVO84WAgAApLPQ4UIAAIByFq5pIQAAQDkLDQsBAADSWWiJFAAAoJ2FlkgBAADSWWhcCAAAUM7Cc+cMAACALAQAACCahXuWSAEAAMJZaFoIAAAQz0IfAQAAIJyFa4cUAACgnIXeLQQAAEhnoWEhAABAOgstkQIAAKSz8PMNAAAAylnobCEAAEA6C71mDwAAkM5Cr9kDAACUPT4BAABA2Xu2SAEAAMpZuLZIAQAAylk4jywEAAAIZ+F/z8uFAAAAXa6cAQAASHO2EAAAQBYCAACQzcJvPVABAAAQzsI900IAAIBwFrqHFAAAoMxNpAAAALIQAAAAWQgAAIAsBAAAQBYCAACQ8d54txAAACCchbveLQQAAAhn4ahCAACAchZaIQUAAGhn4QlDAACAcBY6WwgAAJDOwpGFAAAA5Sz8LJECAACUs9ASKQAAQDoLvWYPAACQzsIzLAQAAJCFAAAAND0+AQAAQJlpIQAAQJppIQAAQJqbSAEAAOJZaIkUAACgnIWGhQAAAOksNCwEAABIZ6FpIQAAQJmbSAEAANJMCwEAANpZ+DlcCAAAUM5CVQgAAJDOQs/ZAwAApLPwVhcCAACEs3DWGikAAEA4C1cWAgAAlLPwzhIpAABAOAtNCwEAANJZaFYIAADQzkJdCAAAUM7CsUMKAABQzsKThQAAAOUs9Jo9AABAOgtNCwEAANJZaFoIAACQzkLTQgAAAFkIAABA1OMTAAAAlL3rPXsAAIByFt7aIgUAAAhn4chCAACAdBaOJVIAAIB0FpoWAgAAhLPQrBAAACCdhWaFAAAA6Sw0LQQAAEhnoRtnAAAA0ll4tkgBAABkIQAAANEsXEukAAAA5Sw0LQQAAJCFAAAAVLNQFQIAAKSzcM7hQgAAgHIWrnkhAACALAQAAKCZhWeJFAAAoJyFO6aFAAAA4Sz0QAUAAIAsBAAAIOrxCQAAAMpMCwEAANpZuC4iBQAAKGfhjS4EAAAIZ+F6zh4AAKCchZ6zBwAAkIUAAABks9AOKQAAQDkLx9lCAACAcha6cgYAACCdhc4WAgAApLPQtBAAACCdhYaFAAAA7Sw0LAQAAChn4ZoWAgAAlLNwTAsBAADKWWhYCAAAkM5CS6QAAADpLPwskQIAAJSz0E2kAAAA6SwcS6QAAADpLDQtBAAACHt8AgAAgLL3zhYpAABAOAufxxYpAABAOAtvZSEAAEA4Cz9XkQIAAIS5cgYAACDtXUukAAAAYaaFAAAAae+ts4UAAADhLJyzRAoAABDOQlUIAADQzkLfAAAAoJyFhoUAAADpLPSaPQAAQDoLnS0EAAAo824hAABAmmkhAABAOwu9Zg8AAJDOQtNCAAAAWQgAAECUK2cAAADS3jmHCwEAAMJZuGtgCAAAEM7CkYUAAADlLDxLpAAAAOUs3HEVKQAAQDgLPVABAABQ5mAhAABA2utkIQAAQDsLLZECAACUs3CMCwEAANJZaFoIAAAQ5soZAACAtNdr9gAAAOkstEQKAACQzkLDQgAAgHgWCkMAAIBwFu7aIgUAAAhn4TyyEAAAIJyF5ypSAACAchbaIQUAAEhn4Z0uBAAACGfh7OcrAAAAdLNw19lCAACAcBZaIgUAAEhnoStnAAAA0lnoZCEAAEA6Cz1bCAAAkM7CsUQKAAAgCwEAAKhm4dgiBQAACGehByoAAADSWeg5ewAAgHQWOlsIAACQzsLPEikAAEA5C1cVAgAAlLPQTaQAAADpLLx5fAUAAIBwFjpbCAAAUM5CN5ECAAC0s1AXAgAAyEIAAACiWbjrJlIAAABZCAAAQDMLzxIpAABAOgsNCwEAANJZaFgIAABQzkJHCwEAANJZaFoIAABQ9vgEAAAAshAAAICod5wtBAAAKGehs4UAAACyEAAAgGoWeqACAACgzJUzAAAAaZZIAQAA0kwLAQAA0kwLAQAA2lk4shAAAKCchaoQAAAgnYV3XqgAAAAIZ+GueSEAAIAsBAAAoJmFlkgBAADSWfiZFgIAAJSzcA0LAQAAylnoOXsAAIB0FnrOHgAAoOzxCQAAAMpeRwsBAADaWWiJFAAAoJyFbiIFAABIZ6ErZwAAANJZaFgIAACQzkLDQgAAgHQWmhYCAAC0s/CEIQAAQDgLd62RAgAAhLNwHlkIAAAQzkJRCAAAkM5CZwsBAADaWWhcCAAAUM7CceUMAABAOQtvLZECAACEs3BskQIAAJSz0A4pAABAOgs/3wAAAKCcheNoIQAAQDoLLZECAACUs9CNMwAAAOks9D4FAABAOgtNCwEAANJZaFoIAACQzkLTQgAAgHYWeqECAACgnIW7xoUAAADhLLwzLQQAAAhnoWkhAABAOgtPFgIAAJSzUBQCAACks/D7Pl8BAACgm4VjiRQAAKCchfvIQgAAgHAWeqACAAAgnYU7poUAAADhLDxVCAAAEPb4BAAAAGWvk4UAAADpLHS0EAAAoJ2FxoUAAADlLFynCwEAAMpZ6NlCAACAdBaus4UAAADlLDQtBAAAaGehbwAAAFDOwtWFAAAA5Sz8dCEAAEA5C9edMwAAAOksfDxcCAAAEM5CK6QAAADpLPy+z1cAAADoZqGjhQAAAPEsdLYQAAAgnIV3lkgBAADCWWhaCAAAkM5CN5ECAAC0s/CEIQAAQDgLx02kAAAA5Sw8L1QAAACUs1AUAgAApLPQ2UIAAIB0Fu5jXggAABDOwnG2EAAAoJyFt5ZIAQAAwlk4qhAAAKCchWuJFAAAoJyFn5tIAQAAwh6fAAAAoMxNpAAAAO0sdBMpAABAOgvdRAoAAFDmbCEAAECaByoAAADaWXi2SAEAAMpZ6CZSAACAdBZ6zR4AACCdhYaFAAAAZW4iBQAASHvtkAIAAJSZFgIAAKS93qcAAABIZ+G5cgYAAKCchSMLAQAA0lloiRQAACCdhaaFAAAAYW4iBQAASHvHFikAAEA6C9cWKQAAQDkLH1kIAADQ5WwhAABA2ruWSAEAAMpZeOfKGQAAAFkIAABAMwstkQIAAKSz0KwQAAAgnYVeswcAAGhnoR1SAAAAWQgAAEA0C+2QAgAAtLNwhSEAAEA4C9cWKQAAQDkLPWcPAABQ9vgEAAAAZe+uJVIAAIAu00IAAIC0dx7TQgAAgHAWunIGAACgnYUjCwEAAMJZOK6cAQAAKGeh5+wBAADaWWhaCAAAUM5CV84AAAC0s9CVMwAAAOUsdOUMAABAOwsNCwEAANJZaFgIAAAQ9vgEAAAAZa+LSAEAANJZaIkUAABAFgIAAJDNQkukAAAA6Sw0LQQAAEhnoTtnAAAA0lm4xoUAAADlLHxkIQAAQDgLzxIpAABAOQvXEikAAEDY4xMAAACUvVZIAQAAykwLAQAA0rxbCAAAEM/CNTAEAABIZ6GbSAEAAMpZaIkUAAAgnYWmhQAAAGEOFgIAAKS9dkgBAADSWTh2SAEAAGQhAAAA1Sy0RQoAAJDOQuNCAACAdBbu5ysAAAB0s3DXEikAAEA4C+8skQIAAJSz0LQQAACgnIVjWggAAFDOQtNCAACAdBbumhYCAADIQgAAAJpZ6GghAABAOws/z9kDAACEs3DmF18BAACgm4XOFgIAAKSzcM4DFQAAAOUsNC0EAABoZ6GPAAAAUM5CO6QAAADpLDQtBAAAKGeh5+wBAADSWegmUgAAgHQWri1SAACAchbefr4CAABANwtnLZECAACks9ASKQAAQDkLDQsBAADSWagLAQAA0lloiRQAACCdhR6oAAAAKGfhuYkUAACgnIWWSAEAANpZeKaFAAAA5Szcx1cAAADoZuG6cgYAAKCchefdQgAAgHIWeqACAACgzMFCAACAtNcOKQAAQDsL7ZACAACUs/DWuBAAACCchZZIAQAA0lno3UIAAIB0Fs5jXAgAAFDOQmcLAQAA0ll4lkgBAADKWWhaCAAA0M5C00IAAIBwFt6ZFgIAAISzcDxcCAAAkM5CS6QAAADlLFxZCAAAUM7Cs0QKAABQzsK5x1cAAAAoZ6ElUgAAgHIWes4eAACgnYWmhQAAAOUsNCwEAABIZ6FhIQAAgCwEAAAgmoVniRQAAKCchaaFAAAA7Sw0LQQAAEhnoWkhAACALAQAAKCahZZIAQAA0lloWggAACALAQAAqGahhwsBAADSWbjGhQAAALIQAACAZhaKQgAAgHYWmhYCAACUs/BcOQMAACALAQAAiGahJVIAAIB0FpoVAgAApLNwdCEAAEA6C+2QAgAAhD0+AQAAQJlpIQAAQD0LdSEAAEA5C71bCAAAkM5Cw0IAAIB2FupCAACALjeRAgAApL1rWggAAFDOQkukAAAA6Sy87/MVAAAAwlnoGwAAAJSzcF06AwAAkM5CDxcCAACUs9CVMwAAAOksvHO6EAAAIJyFs7IQAACgnIXOFgIAAKSz0BIpAABAOgtdOQMAABDm1UIAAIA000IAAIB6FjpbCAAAUM7CMy0EAAAoZ+GYFgIAAHS5cgYAACDtPe8WAgAAlLNw3UQKAAAgCwEAAIhm4blyBgAAoJyFM6aFAAAA4Sy0QwoAAJDOQheRAgAApLPQDikAAECZ5+wBAABkIQAAALIQAACAoNezhQAAAO0sdOUMAACALAQAAKCahZZIAQAA0lloWggAACALAQAAqGahJVIAAIB0FpoWAgAAhHnOHgAAQBYCAAAgCwEAAAh659w5AwAAUM7CdecMAABAOQutkQIAAJSzcL1QAQAAUM7C8Z49AABAOgudLQQAAEhnoWEhAABAOgsNCwEAANJZaFoIAACQzkLTQgAAAFkIAABANQstkQIAAKSz0LQQAAAg7PEJAAAAyt6zRAoAAFDOwrVECgAAUM5CZwsBAABkIQAAANUstEQKAACQzkJXzgAAAKSz0LQQAAAgnYWGhQAAAGV7tkgBAADCfgfp3Bt9oa9MdAAAAABJRU5ErkJggg==',
            'text/plain': ['<IPython.core.display.Image object>'],
          },
          metadata: {
            jdh: {
              module: 'object',
              object: {
                source: ['Process of creating an article in the Journal of Digital History'],
                type: 'image',
              },
            },
          },
          output_type: 'display_data',
        },
      ],

      source: [
        'from IPython.display import Image \n',
        'metadata={\n',
        '    "jdh": {\n',
        '        "module": "object",\n',
        '        "object": {\n',
        '            "type":"image",\n',
        '            "source": [\n',
        '                "Website: Docker Desktop installation for Windows"\n',
        '            ]\n',
        '        }\n',
        '    }\n',
        '}\n',
        'display(Image("media/Docker_Desktop3.png"), metadata=metadata)',
      ],
    },
  ],
}
