import React from 'react'
import ToC from '../components/ToC'

export default {
  component: ToC,
  title: 'Table of Contents',
  argTypes: {
    steps: { control: { type: 'object' } },
    onClick: { action: 'clicked' },
  },
}

const Template = (args) => {
  return <ToC {...args} />
}

export const Default = Template.bind({})
export const ActiveBelow = Template.bind({})

ActiveBelow.args = {
  width: 200,
  style: { height: 150 },
  steps: [
    {
      id: 2,
      label: 'figure 1',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: true,
      isSectionEnd: true,
      count: 1,
    },
    {
      id: 4,
      label: 'Step 1: (Windows) Setup the writing environment',
      isFigure: false,
      isHermeneutics: false,
      level: 'H2',
      isSectionStart: true,
      isSectionEnd: false,
      count: 2,
    },
    {
      id: 5,
      label: 'A: Install Jupyter Notebook via Docker',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 3,
    },
    {
      id: 9,
      label: 'figure 2',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 4,
      isSelected: true,
    },
    {
      id: 12,
      label: 'figure 3',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 5,
    },
    {
      id: 13,
      label: 'figure 4',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 6,
    },
    {
      id: 15,
      label: 'figure 5',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 7,
    },
    {
      id: 17,
      label: 'figure 6',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 8,
      active: true,
    },
    {
      id: 19,
      label: 'figure 7',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 9,
    },
    {
      id: 21,
      label: 'figure 8',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 10,
    },
    {
      id: 22,
      label: 'B: Use the terminal to test the getting-started guide',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 11,
    },
  ],
}

Default.args = {
  width: 200,
  className: 'h-100',
  steps: [
    {
      id: 2,
      label: 'figure 1',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: true,
      isSectionEnd: true,
      count: 1,
    },
    {
      id: 4,
      label: 'Step 1: (Windows) Setup the writing environment',
      isFigure: false,
      isHermeneutics: false,
      level: 'H2',
      isSectionStart: true,
      isSectionEnd: false,
      count: 2,
    },
    {
      id: 5,
      label: 'A: Install Jupyter Notebook via Docker',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 3,
      active: true,
    },
    {
      id: 9,
      label: 'figure 2',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 4,
      isSelected: true,
    },
    {
      id: 12,
      label: 'figure 3',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 5,
    },
    {
      id: 13,
      label: 'figure 4',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 6,
    },
    {
      id: 15,
      label: 'figure 5',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 7,
    },
    {
      id: 17,
      label: 'figure 6',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 8,
    },
    {
      id: 19,
      label: 'figure 7',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 9,
    },
    {
      id: 21,
      label: 'figure 8',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 10,
    },
    {
      id: 22,
      label: 'B: Use the terminal to test the getting-started guide',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 11,
    },
    {
      id: 25,
      label: 'figure 9',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 12,
    },
    {
      id: 27,
      label: 'figure 10',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 13,
    },
    {
      id: 29,
      label: 'figure 11',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 14,
    },
    {
      id: 31,
      label: 'figure 12',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 15,
    },
    {
      id: 33,
      label: 'figure 13',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 16,
    },
    {
      id: 35,
      label: 'figure 14',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: true,
      count: 17,
    },
    {
      id: 36,
      label: 'Step 2: (Windows) Setup the Github repository',
      isFigure: false,
      isHermeneutics: false,
      level: 'H2',
      isSectionStart: true,
      isSectionEnd: false,
      count: 18,
    },
    {
      id: 39,
      label: 'A: Install Github Desktop and sign up for an account',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 19,
    },
    {
      id: 41,
      label: 'figure 15',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 20,
    },
    {
      id: 43,
      label: 'figure 16',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 21,
    },
    {
      id: 44,
      label: 'B: Clone the jdh-jupyter stack and connect it with Docker',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 22,
    },
    {
      id: 46,
      label: 'figure 17',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 23,
    },
    {
      id: 48,
      label: 'figure 18',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 24,
    },
    {
      id: 50,
      label: 'figure 19',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 25,
    },
    {
      id: 52,
      label: 'figure 20',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 26,
    },
    {
      id: 54,
      label: 'figure 21',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 27,
    },
    {
      id: 56,
      label: 'figure 22',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 28,
    },
    {
      id: 58,
      label: 'figure 23',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 29,
    },
    {
      id: 59,
      label: 'C: Use the JDH template notebook',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 30,
    },
    {
      id: 63,
      label: 'figure 24',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 31,
    },
    {
      id: 65,
      label: 'figure 25',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 32,
    },
    {
      id: 67,
      label: 'figure 26',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 33,
    },
    {
      id: 69,
      label: 'figure 27',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 34,
    },
    {
      id: 71,
      label: 'figure 28',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 35,
    },
    {
      id: 73,
      label: 'figure 29',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 36,
    },
    {
      id: 75,
      label: 'figure 30',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 37,
    },
    {
      id: 77,
      label: 'figure 31',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 38,
    },
    {
      id: 79,
      label: 'figure 32',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 39,
    },
    {
      id: 81,
      label: 'figure 33',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 40,
    },
    {
      id: 83,
      label: 'figure 34',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 41,
    },
    {
      id: 84,
      label: 'D: Setup the bibliography via the cite2c plugin (Zotero)',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 42,
    },
    {
      id: 86,
      label: 'figure 35',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 43,
    },
    {
      id: 198,
      label: 'Step 2: Data cleaning & streamlining',
      isFigure: false,
      isHermeneutics: true,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 39,
    },
    {
      id: 200,
      label: 'Attribute cleaning and conflation of information',
      isFigure: false,
      isHermeneutics: true,
      level: 'H4',
      isSectionStart: false,
      isSectionEnd: false,
      count: 40,
    },
    {
      id: 201,
      label: 'Regular Expressions as historian’s best friend',
      isFigure: false,
      isHermeneutics: true,
      level: 'H4',
      isSectionStart: false,
      isSectionEnd: false,
      count: 41,
    },
    {
      id: 202,
      label: 'Cleaning of epigraphic text',
      isFigure: false,
      isHermeneutics: true,
      level: 'H4',
      isSectionStart: false,
      isSectionEnd: false,
      count: 42,
    },
    {
      id: 203,
      label: 'Residual cleaning of EDCS inconsistent HTML markup',
      isFigure: false,
      isHermeneutics: true,
      level: 'H4',
      isSectionStart: false,
      isSectionEnd: true,
      count: 43,
    },
    {
      id: 88,
      label: 'figure 36',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 44,
    },
    {
      id: 90,
      label: 'figure 37',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 45,
    },
    {
      id: 92,
      label: 'figure 38',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 46,
    },
    {
      id: 94,
      label: 'figure 39',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 47,
    },
    {
      id: 96,
      label: 'figure 40',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 48,
    },
    {
      id: 98,
      label: 'figure 41',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 49,
    },
    {
      id: 100,
      label: 'figure 42',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 50,
    },
    {
      id: 103,
      label: 'Stop or continue working on your notebook',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 51,
    },
    {
      id: 105,
      label: 'figure 43',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 52,
    },
    {
      id: 107,
      label: 'figure 44',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 53,
    },
    {
      id: 109,
      label: 'figure 45',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 54,
    },
    {
      id: 111,
      label: 'figure 46',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 55,
    },
    {
      id: 113,
      label: 'figure 47',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 56,
    },
    {
      id: 114,
      label: 'figure 48',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 57,
    },
    {
      id: 116,
      label: 'figure 49',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 58,
    },
    {
      id: 119,
      label: 'figure 50',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 59,
    },
    {
      id: 120,
      label: 'Alternate writing environment',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: true,
      count: 60,
    },
    {
      id: 123,
      label: 'Step 1: (Mac) Setup the writing environment',
      isFigure: false,
      isHermeneutics: false,
      level: 'H2',
      isSectionStart: true,
      isSectionEnd: false,
      count: 61,
    },
    {
      id: 124,
      label: 'A: Install Jupyter Notebook via Docker (Mac)',
      isFigure: false,
      isHermeneutics: false,
      level: 'H3',
      isSectionStart: false,
      isSectionEnd: false,
      count: 62,
    },
    {
      id: 128,
      label: 'figure 51',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 63,
    },
    {
      id: 130,
      label: 'figure 52',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 64,
    },
    {
      id: 132,
      label: 'figure 53',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 65,
    },
    {
      id: 134,
      label: 'figure 54',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 66,
    },
    {
      id: 136,
      label: 'figure 55',
      isFigure: true,
      isTable: false,
      isHermeneutics: false,
      level: 'CODE',
      isSectionStart: false,
      isSectionEnd: false,
      count: 67,
    },
  ],
}
