import type { Meta, StoryObj } from '@storybook/react'
import { MemoryRouter } from 'react-router-dom'

import NewArticle from './NewArticle'

const meta: Meta<typeof NewArticle> = {
  title: 'Components/NewArticles/NewArticle',
  component: NewArticle,
  decorators: [
    (Story) => (
      <MemoryRouter>
        <Story />
      </MemoryRouter>
    ),
  ],
  args: {
    article: {
      abstract: {
        pid: 'abc123',
        title:
          'Aligning Technology with Pedagogical Goals: Digital Public History, Content Management Systems, and Minimalist Frameworks ',
        contact_firstname: 'John',
        contact_lastname: 'Doe',
      },
      contributor: [{ content: 'Author name' }],
      publication_date: '2024-10-21T14:37:06+02:00',
      issue: {
        id: 1,
        name: 'Issue test',
        pid: 'jdh001',
        publication_date: '2024-10-21T14:37:06+02:00',
      },
      fingerprint: {
        cells: [
          {
            tags: ['title'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 92,
            firstWords: 'Gaming the Qing Mandarinate: Digital Approaches to a Nineteenth-Century',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['contributor'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 154,
            firstWords: 'Elisabeth Kaske',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['contributor'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 181,
            firstWords: 'Florian Keßler',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['copyright'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 446,
            firstWords: '',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['keywords'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 77,
            firstWords:
              'Qing dynasty (1644-1911), Bureaucracy, Boardgame, Graph Database, Monte Carlo',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['abstract'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2827,
            firstWords: 'How did people in the Qing dynasty (1644–1911) imagine careers',
            isMetadata: true,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-1-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 15,
            firstWords: 'Introduction',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 638,
            firstWords:
              'Our study explores the historical board game Mandarin Promotions (Shengguantu',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2219,
            firstWords: 'Bureaucratic promotion games in China go back to the ninth',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 879,
            firstWords: 'Our study is based on the chart reproduced by Puk',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2125,
            firstWords: 'In a second step, we used Monte Carlo simulations to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1774,
            firstWords: 'Secondly, given that office purchase is the only aspect of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1345,
            firstWords: 'The body of this paper has four main sections. In',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1570,
            firstWords: 'In Equal opportunity?, the center piece of this study executed',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 182,
            firstWords: 'In conclusion, our playful engagement with the Qing mandarinate did',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-2-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 54,
            firstWords: 'Can we study a historical board game as historians?',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1527,
            firstWords: 'Mandarin Promotions was a board game most typically played during',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 392,
            firstWords: 'During the New Year’s holiday of 1887, when the Qing',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 176,
            firstWords: '\nTake easy a dice bowl, set a square buffet.',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 437,
            firstWords: 'There is a double denial of realism in this poem.',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2067,
            firstWords: 'This paper reflects a similar tension. Can we draw up',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1557,
            firstWords: 'In fact, for better or worse, historians have long used',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1755,
            firstWords: 'Bureaucratic promotion games have a long history in China. The',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 3086,
            firstWords: 'Others have understood Mandarin Promotions as a social commentary and',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2499,
            firstWords: 'Some of our inspiration comes from sociologists and anthropologists who',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1223,
            firstWords: 'We think that it is not too far-fetched to see',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 993,
            firstWords: 'Central to our approach to the game is hence to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1183,
            firstWords: 'The third bureaucracy is the actual lived bureaucracy, as shown',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 506,
            firstWords: 'After explaining the basic set-up of the game and our',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-3'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 43,
            firstWords: 'Introducing the Game and our Data Model¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 43,
            firstWords: 'The Game Chart as an Imperial Metaphor¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 588,
            firstWords: 'Mandarin Promotions (Shengguantu 陞官圖) belongs to the family of “life',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-game-chart-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 309,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 852,
            firstWords: 'The layout is circular and concentric, resembling a monarchic cosmos:',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 631,
            firstWords: 'From the rim toward the center, sixty-six departments are arranged',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 278,
            firstWords: 'In total, 434 positions are distributed across these 66 departments.',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-32-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 32,
            firstWords: 'Playing Mandarin Promotions¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 188,
            firstWords: 'Mandarin Promotions is a board game played with dice—in our',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 55,
            firstWords: 'Starting the Game: Chushen and Hereditary Titles',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 341,
            firstWords: 'Unlike other life games with a single point of “birth”',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 700,
            firstWords:
              'The fifteen chushen starting positions represent various social origins or',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 348,
            firstWords: 'In the symbolic logic of the chart, social origins are',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-23-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 35,
            firstWords: 'Movement and Dice Combinations',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 571,
            firstWords: 'Like most life games, Mandarin Promotions is driven by dice',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 513,
            firstWords: 'There are twenty-five basic dice combinations: six each for two-equals',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 502,
            firstWords: 'Triples (only used to access starting positions), all-equals, and the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 39,
            firstWords: 'Money, Wagers, and Office Purchase',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 689,
            firstWords:
              'Mandarin Promotions (in its nineteenth-century version) was played both for',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 459,
            firstWords: 'The most consequential rule printed in the center of the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 24,
            firstWords: 'Climbing the Ladder',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 711,
            firstWords: 'To enter the game proper, each player’s first throw assigns',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 892,
            firstWords: 'Of the 434 total positions, 338 are accessible to the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 42,
            firstWords: 'Temporary Positions and Special Rules',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 454,
            firstWords: 'Ninety-six positions on the game chart are designated as temporary',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 843,
            firstWords: 'They correspond to three institutions in the Qing bureaucracy:',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 27,
            firstWords: 'Memory and Eligibility',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 527,
            firstWords:
              'Certain promotions or transfers are conditional upon having previously visited',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 17,
            firstWords: 'Translations',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 724,
            firstWords: 'For the translation of official titles and institutions, this study',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-34-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 37,
            firstWords: 'Career paths as network and tree¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1023,
            firstWords: 'Based on its characteristics, it is possible to re-imagine *Mandarin',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1321,
            firstWords: 'The network structure obtained in this way is not a',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 357,
            firstWords: 'A condensed version of the resulting graph is shown in',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['hermeneutics'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 31,
            firstWords: '\ncall db.schema.visualization()',
            isMetadata: false,
            isHermeneutic: true,
          },
          {
            tags: ['figure-32-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 274,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1170,
            firstWords: 'Since Neo4J proved too unwieldy to be handled for further',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 764,
            firstWords: 'Here is where a programmatic approach proved superior. Based on',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-4-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 65,
            firstWords: '“Utopias of Rules”? The Real and the Gamified Qing',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 51,
            firstWords: 'Official Rules: The Examination of Rank-Classes',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 390,
            firstWords: 'If we argue that Mandarin Promotions is both mimicry of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 871,
            firstWords: 'We have cited player opinion in the poem at the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1539,
            firstWords: 'That designer did not cite his name does not mean',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1302,
            firstWords:
              'The Collected Statutes mostly contain regulations and imperial decisions on',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1362,
            firstWords: 'As the main outline of regular career promotions the statutory',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 987,
            firstWords: 'As a proof of concept, we may use a network',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-321-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 315,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-321-transl-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 315,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 760,
            firstWords: 'This graph (Figures 3 and 4) first shows a high',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2343,
            firstWords: 'Even though modularity is not a precise measure, the data',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-1-*', 'data-table'],
            type: 'code',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 81,
            firstWords:
              'import pandas\n pandas.read_csv("script/Table 1 PJK_Gephi_Analysis_Modularity.csv")',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1199,
            firstWords: 'Graph theory knows many types of centralities. In accordance with',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-42-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 44,
            firstWords: 'Game Rules: Plotting Mandarin Promotions',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2558,
            firstWords:
              'Theoretically, centralities could help to compare Mandarin Promotions to official',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 599,
            firstWords: 'The following graph (Figure 5, Chinese, and Figure 6, English)',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-322-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 359,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-322-transl-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 360,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 393,
            firstWords: 'As discussed above, the greater differentiation of positions creates very',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1188,
            firstWords: 'Nevertheless, we do see parallels to “Examination” in the global',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-2-*', 'data-table'],
            type: 'code',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 80,
            firstWords:
              'pandas.read_csv("script/Table 2 SGT2_Gephi_Analysis_Betweenness_Modularity.csv")',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 701,
            firstWords: 'In addition, the game shows two more isolated clusters among',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-43-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 34,
            firstWords: 'Realism: The Case of Prefects¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 736,
            firstWords:
              'In network terms, the above explorations are “graph-global” questions, pertaining',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 757,
            firstWords: 'For the first question, we examine the case of prefect',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1611,
            firstWords: 'In the Qing administrative system, the prefecture is a unit',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 956,
            firstWords: 'Wu Yue, one of the most exacting scholars of Qing',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 551,
            firstWords: 'We could argue that a board game is fictional, because',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 852,
            firstWords: 'For this purpose, we examined who could be appointed to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-32-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1606,
            firstWords: '|Examination of Rank-Classes ((A Gui 阿桂, 2000)) |Mandarin',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 592,
            firstWords: 'In Table 3 we see that in some cases “Examination”',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2057,
            firstWords: 'The most interesting difference is in the existence of the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 366,
            firstWords: 'What did prefect appointments really look like on the ground?',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-prefect-origins-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 296,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 354,
            firstWords: 'In Figure 7, we find two differences from the regulations',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2043,
            firstWords: 'The Investigating Censor (rank-class 5b) was a pivotal position, and,',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 922,
            firstWords: 'The second unexpected candidate for prefect was the county magistrates',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 919,
            firstWords: 'We have already seen that Mandarin Promotions follows the “Examination',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-33-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 450,
            firstWords: '|County Magistrate|Great Reckoning verdict|Appointed to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 999,
            firstWords: 'In other words, the game behaves exactly as Wu Yue',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 440,
            firstWords: 'In addition, the rules of the game also allowed for',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1516,
            firstWords: 'So, what does the case of prefect tell us about',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 34,
            firstWords: 'Value: The Case of Ministries¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 303,
            firstWords: 'As we have argued above, all designations listed on the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 940,
            firstWords: 'One example is the distribution of the Six Ministries in',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 584,
            firstWords: 'In Mandarin Promotions, each ministry is listed with its full',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 690,
            firstWords: 'For this, we again turn to a graph-local question and',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-341-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 260,
            firstWords: 'Merit|War|Works|Revenue|Rites|Punishments|Personnel|',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-34-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 897,
            firstWords: 'On the surface, the distribution of merit scores between the',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 315,
            firstWords: 'This trend is more pronounced for the three entry-level positions',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-342-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 980,
            firstWords:
              '||郎中, 5a, Department Director|員外郎, 5b, Vice Department Director|主事, 6a, Secretary|Totals',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 79,
            firstWords: 'They can better be visualized in a radar chart as',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-342-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 323,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1678,
            firstWords: 'The Ministries of Revenue, Punishments and Works stand out with',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 763,
            firstWords: 'These three tests are limited in scope, but readers can',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-5-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 59,
            firstWords: 'Equal opportunity? Do all players have a chance to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 13,
            firstWords: 'Chushen',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 693,
            firstWords: 'Chushen is a term hard to translate. It is most',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 762,
            firstWords: 'In Mandarin Promotions, commoners remain “outside the game” (juwai 局外,',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 923,
            firstWords: 'Fifteen of the chushen positions are in a department on',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-41-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1376,
            firstWords: 'Dice|Compartment|Position|Translation|Category',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1455,
            firstWords: 'Confining ourselves to the fifteen positions in the “Chushen” department',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-52-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 12,
            firstWords: 'Purchase',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-4-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 787,
            firstWords: 'In the life-world of the game designer, the legal sale',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1644,
            firstWords: 'Office purchase is the only element that returns agency to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1331,
            firstWords:
              'Few specifics concerning the procedure and advisability of office purchase',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['figure-4.2-*'],
            type: 'code',
            isTable: false,
            isFigure: true,
            countRefs: 0,
            isHeading: false,
            countChars: 281,
            firstWords: 'from IPython.display import Image\n metadata={\n',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 336,
            firstWords: 'Late nineteenth-century game boards also created a new category of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 941,
            firstWords: 'The list of offices for sale is telling. These positions',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-42-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1030,
            firstWords: 'The introduction of the holding category again mirrors reality where',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 492,
            firstWords: 'In game terms, on the other hand, introducing the holding',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 953,
            firstWords: 'Our simulation will try to determine under which circumstances purchase',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 320,
            firstWords: 'Since the overt game rules are incomplete, we had to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 349,
            firstWords: 'Firstly, special rules apply to P8 (Student of Astronomy) and',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1318,
            firstWords: 'Secondly, in the real Qing world, all office purchasers had',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1361,
            firstWords: 'Thirdly, we have to clarify unclear or incomplete rules in',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 64,
            firstWords: 'Technical Background: Monte Carlo and the Rules of Purchase¶',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1214,
            firstWords: 'Analysing the question of opportunities in the game, both with',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 476,
            firstWords: 'Another possibility for the analysis of a game would be',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 400,
            firstWords: 'Hence, we have decided to pursue a straightforward yet effective',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1184,
            firstWords: 'In practical terms, in order to conduct the Monte Carlo',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-subsection-54-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 39,
            firstWords: 'Simulation Results without Purchase',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 702,
            firstWords: 'Using the implementation of the game in Python, it is',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['hermeneutics'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 864,
            firstWords: 'In the following, we want to use this data to',
            isMetadata: false,
            isHermeneutic: true,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 389,
            firstWords: 'In each playthrough, all players start – just as in',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 743,
            firstWords: 'First, we consider how long it takes players starting from',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-441-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 2007,
            firstWords: '| Dice | Position | Translation | Average number of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1689,
            firstWords: 'Table 8 also contains a column showing average effective money.',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 481,
            firstWords: 'Among the other positions, the only chushen that on average',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 725,
            firstWords: 'On the other end of the spectrum, the positions that',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1373,
            firstWords: 'Finally, looking at the average final rank that players starting',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 979,
            firstWords: 'Aside from starting positions, we can also group the data',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-442-*'],
            type: 'markdown',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 253,
            firstWords:
              'Did go through examination system?|Average number of hops until retirement|Average',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 746,
            firstWords: 'Overall, our findings reveal that for all chushen positions, except',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 749,
            firstWords: 'Overall, our findings reveal that for all chushen positions, except',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 38,
            firstWords: 'When would purchase be lucrative?',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 574,
            firstWords: 'In the preceding section we have analysed the role of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1033,
            firstWords: 'In general, the question under which circumstances office purchase is',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1453,
            firstWords: 'Hence, for the purposes of this study, we decided to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1666,
            firstWords: 'Since our interpretation of the rules allows the players to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 422,
            firstWords:
              'Even given these simplifications, the decision strategy outlined above requires',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1389,
            firstWords: 'As a first result, the algorithm outlined above leads to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1307,
            firstWords: 'One potential implication of allowing purchase in the rules of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 966,
            firstWords: 'However, according to our interpretation of the rules, the more',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['table-451-*', 'data-table'],
            type: 'code',
            isTable: true,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 66,
            firstWords: 'pandas.read_csv("script/Table 10_purchase_simulation_results.csv")',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 425,
            firstWords: 'In summary, our numerical findings do confirm a tendency to',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 416,
            firstWords: 'This confirms the intuition of some modern day editions of',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: ['anchor-section-6-*'],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 14,
            firstWords: 'Conclusions',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 502,
            firstWords: 'The goal of this paper has been twofold: First, we',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 674,
            firstWords: 'In order to answer these questions, we have used two',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 667,
            firstWords: 'We found that the game was both a mimicry and',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 1035,
            firstWords: 'At the same time, our simulation of the experiences made',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: true,
            countChars: 19,
            firstWords: 'Acknowledgements',
            isMetadata: false,
            isHermeneutic: false,
          },
          {
            tags: [],
            type: 'markdown',
            isTable: false,
            isFigure: false,
            countRefs: 0,
            isHeading: false,
            countChars: 274,
            firstWords: 'Elisabeth Kaske wishes to thank Puk Wing Kin and Jacob',
            isMetadata: false,
            isHermeneutic: false,
          },
        ],
        stats: {
          countRefs: 0,
          countCells: 182,
          countChars: 136651,
          extentRefs: [0, 0],
          extentChars: [12, 3086],
          countHeadings: 29,
          countCodeCells: 12,
          countContributors: 2,
          countHermeneuticCells: 2,
        },
      },
    },
  },
}

export default meta
type Story = StoryObj<typeof NewArticle>

export const Default: Story = {}
