export const statusIcons: Record<string, { icon: string }> = {
  accepted: { icon: 'error' },
  submitted: { icon: 'error' },
  suspended: { icon: 'error' },
  error: { icon: 'error' },
  abandoned: { icon: 'cancel' },
  declined: { icon: 'cancel' },
  draft: { icon: 'error' },
  technical_review: { icon: 'error' },
  peer_review: { icon: 'error' },
  design_review: { icon: 'error' },
  copy_editing: { icon: 'error' },
  published: { icon: 'check_circle' },
  social: { icon: 'error' },
  archived: { icon: 'check_circle' },
}
