version: '3.7'
services:
  jdh:
    container_name: jdh
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:z
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      GIT_TAG: ${GIT_TAG}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_VERSION: ${GIT_VERSION}
    stdin_open: true