name: Build and publish Docker image for Release
on:
  # Trigger the workflow on push or pull request,
  # for the develop branch and all new tags
  push:
    tags:
      - v*
      - preview-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Prune Unshallow Tags
      run: git fetch --prune --unshallow --tags
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Extract commit hash
      shell: bash
      run: echo "##[set-output name=hash;]$(git rev-parse --short ${GITHUB_SHA})"
      id: extract_hash
    - name: Extract latest tag
      shell: bash
      run: echo "RELEASE_VERSION="$(git describe --tags --abbrev=0 ${GITHUB_SHA}) >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        GIT_TAG: ${{ env.RELEASE_VERSION }}
        GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        GIT_REVISION: ${{ steps.extract_hash.outputs.hash }}
      with:
        name: c2dhunilu/journal-of-digital-history
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        buildargs: GIT_TAG,GIT_BRANCH,GIT_REVISION
        tags: "${{ env.RELEASE_VERSION }}"
