name: 'Storybook Tests'
on:
  push:
    branches:
      - develop
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '^18.9.0'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
